name: Download Sumomo Binary
description: Download sumomo binary from artifact or release

inputs:
  platform-name:
    description: 'Platform name (e.g., ubuntu-22.04_x86_64, windows_x86_64, macos_arm64)'
    required: true
  branch-name:
    description: 'Branch name to search for artifacts'
    required: true

runs:
  using: composite
  steps:
    - name: Download sumomo artifact
      shell: bash
      run: |
        # workflow_call で呼び出された場合は、現在のワークフロー実行から artifact をダウンロード
        if [ "${{ github.event_name }}" = "workflow_call" ]; then
          echo "workflow_call から呼び出されました。現在のワークフロー実行から artifact をダウンロードします"

          # 現在のワークフロー実行 ID を取得
          # workflow_call の場合、github.run_id は呼び出し元のワークフロー実行 ID を指す
          CURRENT_RUN_ID="${{ github.run_id }}"
          echo "現在のワークフロー実行 ID: $CURRENT_RUN_ID"

          # 呼び出し元のワークフロー実行から artifact をダウンロード
          gh run download $CURRENT_RUN_ID --name examples_${{ inputs.platform-name }} --dir ./sumomo_binary
        else
          # workflow_call 以外の場合は、同一ブランチの最新の成功したビルドワークフローの実行を取得
          RUN_ID=$(gh run list --workflow=build.yml --branch=${{ inputs.branch-name }} --status=success --limit=1 --json databaseId --jq '.[0].databaseId')

          if [ -n "$RUN_ID" ]; then
            echo "ブランチ ${{ inputs.branch-name }} の成功したビルドが見つかりました: $RUN_ID"
            # アーティファクトをダウンロード
            gh run download $RUN_ID --name examples_${{ inputs.platform-name }} --dir ./sumomo_binary
          else
            echo "ブランチ ${{ inputs.branch-name }} の成功したビルドが見つかりません"
            echo "VERSION ファイルから release バージョンを取得してダウンロードします"

            # VERSION ファイルからバージョンを取得
            VERSION=$(cat VERSION | head -n1)
            echo "VERSION: $VERSION"

            # プラットフォームに応じたアーカイブ形式を決定
            if [[ "${{ inputs.platform-name }}" == windows_* ]]; then
              ARCHIVE_NAME="sumomo_${{ inputs.platform-name }}.zip"
            else
              ARCHIVE_NAME="sumomo_${{ inputs.platform-name }}.tar.gz"
            fi

            echo "リリース $VERSION から $ARCHIVE_NAME をダウンロードします"

            # リリースアセットをダウンロード
            gh release download "$VERSION" --pattern "$ARCHIVE_NAME"

            # アーカイブを展開
            mkdir -p sumomo_binary

            if [[ "${{ inputs.platform-name }}" == windows_* ]]; then
              # Windows の場合は zip を展開
              unzip -q "$ARCHIVE_NAME" -d .
              mv "sumomo_${{ inputs.platform-name }}"/* sumomo_binary/
            else
              # Linux/macOS の場合は tar.gz を展開
              tar -xzf "$ARCHIVE_NAME" -C sumomo_binary --strip-components=1
            fi

            # ダウンロードしたアーカイブを削除
            rm "$ARCHIVE_NAME"
          fi
        fi
      env:
        GH_TOKEN: ${{ github.token }}

    - name: Setup sumomo binary
      shell: bash
      run: |
        # ダウンロードしたバイナリを確認
        ls -la sumomo_binary/

        # sumomo.py が期待するディレクトリ構造を作成
        mkdir -p examples/_build/${{ inputs.platform-name }}/release/sumomo/

        # プラットフォームに応じたバイナリ名を決定
        if [[ "${{ inputs.platform-name }}" == windows_* ]]; then
          BINARY_NAME="sumomo.exe"
        else
          BINARY_NAME="sumomo"
        fi

        # sumomo バイナリを期待される場所に配置
        # raspberry_pi の場合は libcamera などの共有ライブラリも含めてすべてコピー
        if [[ "${{ inputs.platform-name }}" == "raspberry-pi-os_armv8" ]]; then
          cp -r sumomo_binary/* examples/_build/${{ inputs.platform-name }}/release/sumomo/
        else
          cp sumomo_binary/$BINARY_NAME examples/_build/${{ inputs.platform-name }}/release/sumomo/
        fi

        # Linux/macOS の場合は実行権限を付与
        if [[ "${{ inputs.platform-name }}" != windows_* ]]; then
          chmod +x examples/_build/${{ inputs.platform-name }}/release/sumomo/$BINARY_NAME
        fi

        # パスを確認
        ls -la examples/_build/${{ inputs.platform-name }}/release/sumomo/$BINARY_NAME
